"""Migrate an existing `.kicad_sch` into the schematic-as-code workflow.

Run once per board. Given `foo.kicad_sch` it produces, alongside it:

  foo.base.kicad_sch   frozen capture of the original — the source material the
                       generator builds on. Committed; never edit by hand or open
                       in KiCad. (Editing happens in foo_sch.py.)
  uuids.json           registry seeded with the root schematic uuid and every
                       component's uuid, keyed by reference designator.
  foo_sch.py           the new source of truth: loads the frozen base, applies
                       your edits (none yet), and writes foo.kicad_sch.
  foo.kicad_sch        regenerated working file — open THIS in KiCad to lay out
                       the PCB.

Why a frozen base rather than loading foo.kicad_sch in place: the generator appends
new elements, so re-applying edits on the same file it writes would duplicate them.
Loading an immutable base makes regeneration deterministic and idempotent, and —
because the engine round-trips untouched trees byte-for-byte — a freshly migrated
board with no edits regenerates with zero UUID churn, so the PCB layout is safe.

Usage:
    python -m hardware.schematic.migrate hardware/leg/leg_v2.kicad_sch
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from . import sexpr
from .registry import UuidRegistry


def _reference(symbol_node):
    for p in symbol_node.find_all("property"):
        if p.items[1].value == "Reference":
            return p.items[2].value
    return None


def _summarize(root):
    comps, nets = [], set()
    for s in root.find_all("symbol"):
        ref = _reference(s)
        val = next((p.items[2].value for p in s.find_all("property")
                    if p.items[1].value == "Value"), "")
        lib = s.find("lib_id").items[1].value
        if ref:
            comps.append((ref, lib, val))
    for l in root.find_all("global_label"):
        nets.add(l.items[1].value)
    comps.sort(key=lambda c: (c[0][0], c[0]))
    return comps, sorted(nets)


_TEMPLATE = '''"""Schematic source of truth for `{name}`.

Generated by hardware/schematic/migrate.py from {orig}. Edit THIS file (not the
.kicad_sch and not the .base) to change the schematic, then run it to regenerate
{name}.kicad_sch. Open the regenerated .kicad_sch in KiCad to lay out the PCB.

REMEMBER: update the board documentation in the same change as any edit here
(see .claude/skills/hardware-schematics/SKILL.md).

Components captured at migration:
{comp_lines}

Nets (global labels) captured at migration:
{net_lines}
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
# Make `hardware.schematic` importable when run as a plain script from any cwd.
sys.path.insert(0, str(HERE.parent.parent))

from hardware.schematic import Schematic, UuidRegistry

NAME = "{name}"


def build() -> Schematic:
    reg = UuidRegistry(HERE / "uuids.json")
    sch = Schematic.load(HERE / f"{{NAME}}.base.kicad_sch", reg, name=NAME)

    # --- your edits go here -------------------------------------------------
    # Example: add a status LED on a free pin.
    #   sch.import_lib_symbol(KICAD_R_SMALL_LIB, "Device:R_Small")
    #   r = sch.place("Device:R_Small", "R99", at=(50, 50), value="470", rotation=90)
    #   d = sch.place("Device:LED_Small", "D99", at=(45, 50))
    #   sch.net("STATUS_LED", [r.pin("2"), d.pin("A")])
    # ------------------------------------------------------------------------

    return sch


if __name__ == "__main__":
    build().write(HERE / f"{{NAME}}.kicad_sch")
    print(f"wrote {{NAME}}.kicad_sch")
'''


def migrate(src_path: str, name: str | None = None) -> None:
    src = Path(src_path)
    name = name or src.stem
    out_dir = src.parent
    root = sexpr.load(src)

    # 1. Freeze the original as the build base.
    base_path = out_dir / f"{name}.base.kicad_sch"
    shutil.copyfile(src, base_path)

    # 2. Seed the registry with the root + every component uuid.
    reg = UuidRegistry(out_dir / "uuids.json")
    reg.seed(f"root:{name}", root.find("uuid").items[1].value)
    seeded = 0
    for s in root.find_all("symbol"):
        ref = _reference(s)
        uid = s.find("uuid")
        if ref and uid:
            reg.seed(f"sym:{ref}", uid.items[1].value)
            seeded += 1
    reg.save()

    # 3. Emit the source-of-truth script.
    comps, nets = _summarize(root)
    comp_lines = "\n".join(f"  {r:<8} {lib:<40} {v}" for r, lib, v in comps) or "  (none)"
    net_lines = "\n".join(f"  {n}" for n in nets) or "  (none)"
    script = _TEMPLATE.format(
        name=name, orig=src.name, comp_lines=comp_lines, net_lines=net_lines
    )
    script_path = out_dir / f"{name}_sch.py"
    script_path.write_text(script, encoding="utf-8", newline="\n")

    print(f"froze    {base_path}")
    print(f"seeded   {out_dir / 'uuids.json'} ({seeded} symbols + root)")
    print(f"wrote    {script_path}")
    print(f"next:    python {script_path}   (regenerates {name}.kicad_sch)")


def main():
    ap = argparse.ArgumentParser(description="Migrate a .kicad_sch into code.")
    ap.add_argument("schematic", help="path to the existing .kicad_sch")
    ap.add_argument("--name", default=None, help="board name (default: file stem)")
    args = ap.parse_args()
    migrate(args.schematic, args.name)


if __name__ == "__main__":
    main()
